export const followUpFields = [
    { label: 'ID', value: 'id' },
    { label: 'Matrícula', value: 'enrollment' },
    { label: 'Nome', value: 'name' },
    { label: 'Email', value: 'email' },
    { label: 'Permitir Emails', value: 'allowEmails' },
    { label: 'Telefone', value: 'phoneNumber' },
    { label: 'Contar Trajetória?', value: 'tellTrajectory' },
    { label: 'Trabalhou Antes?', value: 'workedBefore' },
    { label: 'Nível de Formação', value: 'degreeLevel' },
    { label: 'Comentários', value: 'commentary' },
    { label: 'Ano de Ingresso', value: 'entryYear' },
    { label: 'Ano de Conclusão', value: 'graduationYear' },
    { label: 'Situação', value: 'survey.situation' },
    { label: 'Cargo atual', value: 'survey.positionName' },
    { label: 'Tipo do Emprego Atual', value: 'survey.employmentType' },
    { label: 'Trabalha na Área de Formação?', value: 'survey.worksInArea' },
    { label: 'Requisito da Formação no Cargo Atual', value: 'survey.positionEducationRequirement' },
    { label: 'Curso Externo?', value: 'survey.externalCourseName' },
    { label: 'Relação com o Curso Anterior', value: 'survey.courseRelationLevel' },
    { label: 'Nome da Empresa Atual', value: 'survey.companyName' },
    { label: 'Nome do Curso Externo', value: 'course.name' },
    { label: 'Atualizado em', value: 'updatedAt' },
];